### ISSUE TITLE
Invalid initialisation in certain functions

### ISSUE THREAD

**Issue by drondao** [kailigo/LineSegmentMatching#1]
On two member functions of the class "CLineMatching" ("description" and "description_fans", LineMatching.h), an optional Mat variable is initialised in the declaration as "Mat &desMat = Mat()". This goes against C++ rules as you cannot initialise a non-const reference with an rvalue. Cannot compile the code on my end due to this error. This happens too for the member "diffSet" in the CMatOperation class.

**Comment by kailigo** [comment]
The problem might be caused the different platforms used. I developed this project based on OpenCV2.4.3+CMake, on a Win10 machine. I think it would not be difficult to solve this problem. I will fix the problem later.
